runConfig:
  memoryMiB: 1024
  cpu: 1
  minInstances: 0
  maxInstances: 5
  concurrency: 1000

env:
  - variable: API_KEY
    secret: projects/555666777/secrets/API_KEY
  - variable: JWT_SECRET
    secret: projects/555666777/secrets/JWT_SECRET
  - variable: DATABASE_HOST
    value: my-project-staging:us-central1:myapp-db-staging
  - variable: ENVIRONMENT
    value: staging
  - variable: DEBUG
    value: "false"

serviceAccount: myapp-staging@my-project-staging.iam.gserviceaccount.com
cloudsqlConnector: my-project-staging:us-central1:myapp-db-staging