#!/bin/bash
set -euo pipefail

# Inputs provided by Bazel action
# $1: Output file path
# $2: Service Name
# $3: Region
# $4: Source
# $5: Service Account
# $6: Is Job (True/False)
# $7: Top level flags file
# $8: Run config flags file
# $9: Env vars flags file
# $10: Secrets flags file
# $11: Additional flags (string)

output_file="$1"
service_name="$2"
region="$3"
source="$4"
service_account="$5"
is_job="$6"
top_level_file="$7"
run_config_file="$8"
env_vars_file="$9"
secrets_file="${10}"
additional_flags="${11:-}"

# Helper to read file content if it exists
read_flags() {
    local file="$1"
    if [[ -f "$file" ]]; then
        cat "$file"
    fi
}

# Start writing the output script
cat > "$output_file" << 'EOF'
#!/bin/bash
set -euo pipefail

# Generated by rules_cloudrun
# This script executes the gcloud deployment command.

# Helper to handle runtime overrides
USE_IMAGE=false
for arg in "$@"; do
    if [[ "$arg" == --image* ]]; then
        USE_IMAGE=true
        break
    fi
done

CMD="gcloud run"
EOF

# Append command type
if [[ "$is_job" == "True" ]]; then
    echo "CMD+=\" jobs deploy $service_name\"" >> "$output_file"
else
    echo "CMD+=\" deploy $service_name\"" >> "$output_file"
fi

# Append Platform (Service only)
if [[ "$is_job" != "True" ]]; then
     echo "CMD+=\" --platform=managed\"" >> "$output_file"
fi

# Append Region
if [[ -n "$region" ]]; then
    echo "CMD+=\" --region=$region\"" >> "$output_file"
fi

# Append Source (conditional on runtime --image)
if [[ -n "$source" ]]; then
    echo "if [ \"\$USE_IMAGE\" = false ]; then" >> "$output_file"
    echo "  CMD+=\" --source=$source\"" >> "$output_file"
    echo "fi" >> "$output_file"
fi

# Append Service Account
if [[ -n "$service_account" ]]; then
    echo "CMD+=\" --service-account=$service_account\"" >> "$output_file"
fi

# Append generated flags
top_level_flags=$(read_flags "$top_level_file")
if [[ -n "$top_level_flags" ]]; then
    # Job specific replacement for cloudsql
    if [[ "$is_job" == "True" ]]; then
        top_level_flags="${top_level_flags//--add-cloudsql-instances=/--set-cloudsql-instances=}"
    fi
    echo "CMD+=\" $top_level_flags\"" >> "$output_file"
fi

run_config_flags=$(read_flags "$run_config_file")
if [[ -n "$run_config_flags" ]]; then
    echo "CMD+=\" $run_config_flags\"" >> "$output_file"
fi

env_vars_flags=$(read_flags "$env_vars_file")
if [[ -n "$env_vars_flags" ]]; then
    echo "CMD+=\" $env_vars_flags\"" >> "$output_file"
fi

secrets_flags=$(read_flags "$secrets_file")
if [[ -n "$secrets_flags" ]]; then
    echo "CMD+=\" $secrets_flags\"" >> "$output_file"
fi

# Append additional flags
if [[ -n "$additional_flags" ]]; then
    echo "CMD+=\" $additional_flags\"" >> "$output_file"
fi

# Final execution block
cat >> "$output_file" << 'EOF'

echo "Executing command:"
echo "$CMD" "$@"
echo ""

# Execute
exec $CMD "$@"
EOF
